### ISSUE TITLE
extra comma Donut.php line 245

### ISSUE THREAD

**Issue by nickolanack** [fundevogel/tiny-phpeanuts#4]
https://github.com/fundevogel/tiny-phpeanuts/blob/477abbc908b496966f4effa41342f66699741ae5/lib/Donut.php#L245

**Comment by S1SYPHOS** [comment]
Thanks, I'll change that and release a patch version!

**// Edit:**
Wait a moment, that comma doesn't do any harm, now does it? Or is it just me being lazy :lizard:

**Comment by nickolanack** [comment]
trailing commas in arrays are ok, but not in method calls - I get the following in php 7.2
```
PHP Parse error:  syntax error, unexpected ')' in /var/www/html/app.geolive/vendor/fundevogel/tiny-phpeanuts/lib/Donut.php on line 246
```

**Comment by S1SYPHOS** [comment]
I'm on it, sorry for the wait
